apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metedata:
  name: autoscaling
  labels:
    env: prod
    owner: OlehMykhasiv
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: maze-wars-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
