apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    env: prod
    owner: OlehMykhasiv
spec:
  type: LoadBalancer
  selector:
    project: maze-wars
  ports:
    - name: maze-wars-listener
      protocol: TCP
      port: 8082
      targetPort: 8080
